version: '3'
services:

  #PHP Service
  app:
    image: sk2022-img
    container_name: sk2022-container
    build: ./
    restart: always
    ports:
        - "81:80"
    volumes:
      - .:/var/www/html

  #Nginx Service
  myadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    depends_on:
        - mysql
    ports:
      - "82:80"
    links:
      - mysql:db

  #MySQL Service
  mysql:
    image: mysql:5.7.22
    container_name: mysql
    restart: always
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_HOST: 0.0.0.0
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_kudo
      MYSQL_USER: root
      MYSQL_PASSWORD: 2083
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
      # - ./docker/mysql/my.cnf:/etc/mysql/my.cnf


#Docker Networks
# networks:
#   app-network:
#     driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local